name: Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 10
    
    steps:
      - name: 📥 Скачать код
        uses: actions/checkout@v4
      
      - name: 🐍 Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: ⚡ Кэшировать pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      
      - name: 📦 Установить зависимости
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install pyinstaller
      
      - name: 🔨 Собрать EXE
        run: |
          python -m PyInstaller --onefile --windowed --icon=icon.ico --name ZapretUpdater gui.py
      
      - name: 📤 Загрузить EXE
        uses: actions/upload-artifact@v4
        with:
          name: ZapretUpdater
          path: dist/ZapretUpdater.exe